travis:
  secure:
    BINSTAR_TOKEN: szjER8RsMJlvsmlE+GCb/NChDaPerU2L11r+wnfGP3X5lhypDNQZuysz9wNbShbnUHn4GCNsE4aaS8Sev97MH+a76aPQDUdtsiJfaKGb0H+EqPoLnNBYmAtG7P7DC0hJJLgzricfCZHbSVRrHtVmvxQ7pwP8RmQ72BEJblLIWUIn3xl5FKen3lLamEMuFca+XuQbO4UpKnbol6R13Zu7FUln8yl1XqwGPthIOkPjistuQd+UdXLlp+xhaWLDcc12towIfn9x9FTG/ZKyP+ePRqs/RmHlDU0lBdh3SvvSlHZGF0AVFAEUbIJG0SPxA7wb14RJ3I1bGnRefMl+HbourEdUldM8V8bNnz3iI67QdOuu4hUu8YCEpuEgKqg/pnGWXF7IYGai7kjV8m3tDwRJyqQOGtBjZB7u46h8OswNN97k50QTWgNkEIseapeaFhMLIuQpOd/9zuYpNY2sp2trXhTX63m1A0dBG4RkXaR5cnYg8+3vDKOmIlELwTGpLlS782KkOAb8yqg9vK9byQGtXOFLBQb4OTW9T2dR3fJ4atT9rvXmKSuVwYl7MKzX3dJilPlBnoArThAHhFeh52v1ip0FQwoeohKKkSLjL6H1Ft8ADvCZ0xq34p2Iq9Zzn86JzbLlPAUFRCDjAzNwGGQnLxWTbFjyMtpImvIQViNXk88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
